//
//  CustomWorkoutViewController.swift
//  CoreBlastFY
//
//  Created by Riccardo Washington on 6/20/20.
//  Copyright (c) 2020 Riccardo Washington. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CustomWorkoutDisplayLogic: class {
  func displaySomething(viewModel: CustomWorkout.Something.ViewModel)
}

class CustomWorkoutViewController: UIViewController, CustomWorkoutDisplayLogic {
  var interactor: CustomWorkoutBusinessLogic?
  var router: (NSObjectProtocol & CustomWorkoutRoutingLogic & CustomWorkoutDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = CustomWorkoutInteractor()
    let presenter = CustomWorkoutPresenter()
    let router = CustomWorkoutRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = CustomWorkout.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: CustomWorkout.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}
