//
//  CustomWorkoutInteractor.swift
//  CoreBlastFY
//
//  Created by Riccardo Washington on 6/20/20.
//  Copyright (c) 2020 Riccardo Washington. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CustomWorkoutBusinessLogic {
  func doSomething(request: CustomWorkout.Something.Request)
}

protocol CustomWorkoutDataStore {
  //var name: String { get set }
}

class CustomWorkoutInteractor: CustomWorkoutBusinessLogic, CustomWorkoutDataStore {
  var presenter: CustomWorkoutPresentationLogic?
  var worker: CustomWorkoutWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: CustomWorkout.Something.Request)
  {
    worker = CustomWorkoutWorker()
    worker?.doSomeWork()
    
    let response = CustomWorkout.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
