//
//  CustomWorkoutPresenter.swift
//  CoreBlastFY
//
//  Created by Riccardo Washington on 6/20/20.
//  Copyright (c) 2020 Riccardo Washington. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CustomWorkoutPresentationLogic
{
  func presentSomething(response: CustomWorkout.Something.Response)
}

class CustomWorkoutPresenter: CustomWorkoutPresentationLogic
{
  weak var viewController: CustomWorkoutDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: CustomWorkout.Something.Response)
  {
    let viewModel = CustomWorkout.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
