//
//  SettingsPresenter.swift
//  CoreBlastFY
//
//  Created by Riccardo Washington on 2/8/20.
//  Copyright (c) 2020 Riccardo Washington. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SettingsPresentationLogic
{
  func presentItems(response: Settings.Items.Response)
}

class SettingsPresenter: SettingsPresentationLogic
{
  weak var viewController: SettingsDisplayLogic?
  
  // MARK: Do something
  
  func presentItems(response: Settings.Items.Response)
  {
    var viewModel: [Settings.Items.ViewModel.DisplayItem] = []
    let items = response.items
    for item in items {
        let vm = Settings.Items.ViewModel.DisplayItem(title: item.rawValue)
        viewModel.append(vm)
    }
    viewController?.displayItems(viewModel: viewModel)
  }
}
