//
//  SettingsModels.swift
//  CoreBlastFY
//
//  Created by Riccardo Washington on 2/8/20.
//  Copyright (c) 2020 Riccardo Washington. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Settings {
  // MARK: Use cases
  
  enum Items {
    struct Request {
    }
    struct Response {
         enum SettingsItem: String {
                  case about = "About FYF"
                  case notifications = "Notifications"
                  case nutrition = "Nutrition"
                  case foodLog = "Food Log"
                  case parks = "Nearby Parks"
                  case extras = "Extras"
                  case inAppPurchase = "In-App Purchase"
              }
        var items: [SettingsItem] = [
        .about,
        //.notifications,
        .nutrition,
        .foodLog,
        //.parks,
        //.inAppPurchase
        ]
    }
    struct ViewModel {
        struct DisplayItem {
            var title: String
        }
    }
  }
}
