//
//  SettingsInteractor.swift
//  CoreBlastFY
//
//  Created by Riccardo Washington on 2/8/20.
//  Copyright (c) 2020 Riccardo Washington. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SettingsBusinessLogic
{
  func buildItems(request: Settings.Items.Request)
}

protocol SettingsDataStore
{
    var items: [Settings.Items.Response.SettingsItem] { get set }
}

class SettingsInteractor: SettingsBusinessLogic, SettingsDataStore
{
  var presenter: SettingsPresentationLogic?
  
    var items: [Settings.Items.Response.SettingsItem] = []
  
  
  // MARK: Do something
  
  func buildItems(request: Settings.Items.Request) {

    let response = Settings.Items.Response()
    items = response.items
    presenter?.presentItems(response: response)
  }
}
