//
//  WorkoutPresenterTests.swift
//  CoreBlastFY
//
//  Created by Riccardo Washington on 4/16/20.
//  Copyright (c) 2020 Riccardo Washington. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import CoreBlastFY
import XCTest

class WorkoutPresenterTests: XCTestCase {
  // MARK: Subject under test
  
  var sut: WorkoutPresenter!
  
  // MARK: Test lifecycle
  
  override func setUp() {
    super.setUp()
    setupWorkoutPresenter()
  }
  
  override func tearDown() {
    super.tearDown()
    sut = nil
  }
  
  // MARK: Test setup
  
  func setupWorkoutPresenter() {
    sut = WorkoutPresenter()
  }
  
  // MARK: Test doubles
  
  class WorkoutDisplayLogicSpy: WorkoutDisplayLogic {
    var displaySomethingCalled = false
    
    func displayWorkout(viewModel: WorkoutInfo.FetchWorkout.ViewModel) {
      displaySomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testPresentWorkout() {
    // Given
    let spy = WorkoutDisplayLogicSpy()
    sut.viewController = spy

    let response = WorkoutInfo.FetchWorkout.Response(workout: Workout(user: User(), exercises: []))
    
    // When
    sut.presentWorkout(response: response)
    
    // Then
    XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
  }
}
