//
//  WorkoutWorkerTests.swift
//  CoreBlastFY
//
//  Created by Riccardo Washington on 4/16/20.
//  Copyright (c) 2020 Riccardo Washington. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import CoreBlastFY
import XCTest

class WorkoutWorkerTests: XCTestCase {
  // MARK: Subject under test
  
  var sut: WorkoutWorker!
  
  // MARK: Test lifecycle
  
  override func setUp() {
    super.setUp()
    setupWorkoutWorker()
  }
  
  override func tearDown() {
    sut = nil
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupWorkoutWorker() {
    sut = WorkoutWorker(dataStore: [])
  }
  
  // MARK: Test doubles
  
  // MARK: Tests
  
  func testFetchWorkout() {
    // Given
    var mockWorkout: Workout?
    sut.fetchWorkout { (workout) in
        mockWorkout = workout
    }
    // When
    
    // Then
    XCTAssertNotNil(mockWorkout, "MockWorkout shouldn't be nil")
  }
}
