////
////  PreWorkoutWorkerTests.swift
////  CoreBlastFY
////
////  Created by Riccardo Washington on 4/15/20.
////  Copyright (c) 2020 Riccardo Washington. All rights reserved.
////
////  This file was generated by the Clean Swift Xcode Templates so
////  you can apply clean architecture to your iOS and Mac projects,
////  see http://clean-swift.com
////
//
//@testable import CoreBlastFY
//import XCTest
//
//class PreWorkoutWorkerTests: XCTestCase
//{
//  // MARK: Subject under test
//  
//  var sut: PreWorkoutWorker!
//  
//  // MARK: Test lifecycle
//  
//  override func setUp()
//  {
//    super.setUp()
//    setupPreWorkoutWorker()
//  }
//  
//  override func tearDown()
//  {
//    super.tearDown()
//  }
//  
//  // MARK: Test setup
//  
//  func setupPreWorkoutWorker()
//  {
//    sut = PreWorkoutWorker()
//  }
//  
//  // MARK: Test doubles
//  
//  // MARK: Tests
//  
//  func testSomething()
//  {
//    // Given
//    
//    // When
//    
//    // Then
//  }
//}
