//
//  MealDetailsInteractor.swift
//  CoreBlastFY
//
//  Created by Riccardo Washington on 4/25/20.
//  Copyright (c) 2020 Riccardo Washington. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MealDetailsBusinessLogic {
  func passPresenterRecipe(with recipe: Recipe?)
}

protocol MealDetailsDataStore {
  var recipe: Recipe? { get set }
}

class MealDetailsInteractor: MealDetailsBusinessLogic, MealDetailsDataStore {
  var presenter: MealDetailsPresentationLogic?
  var recipe: Recipe?
  
  // MARK: Do something
  
  func passPresenterRecipe(with recipe: Recipe?) {
    guard let recipe = recipe else { return }
    
    let response = MealDetails.RecipeDetails.Response(recipe: recipe)
    presenter?.presentRecipeDetails(response: response)
  }
}
