//
//  MealDetailsRouter.swift
//  CoreBlastFY
//
//  Created by Riccardo Washington on 4/25/20.
//  Copyright (c) 2020 Riccardo Washington. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MealDetailsRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol MealDetailsDataPassing
{
  var dataStore: MealDetailsDataStore? { get }
}

class MealDetailsRouter: NSObject, MealDetailsRoutingLogic, MealDetailsDataPassing
{
  weak var viewController: MealDetailsViewController?
  var dataStore: MealDetailsDataStore?
  
  // MARK: Routing
  
}
