//
//  MealDetailsPresenter.swift
//  CoreBlastFY
//
//  Created by Riccardo Washington on 4/25/20.
//  Copyright (c) 2020 Riccardo Washington. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MealDetailsPresentationLogic {
  func presentRecipeDetails(response: MealDetails.RecipeDetails.Response)
}

class MealDetailsPresenter: MealDetailsPresentationLogic {
  weak var viewController: MealDetailsDisplayLogic?
  
  // MARK: Do something
  
  func presentRecipeDetails(response: MealDetails.RecipeDetails.Response) {
    guard let recipeDetails = response.recipe else { return }
    // present error
    let viewModel = MealDetails.RecipeDetails.ViewModel.RecipeDetails(title: recipeDetails.name, summary: recipeDetails.mealType.rawValue, image: recipeDetails.image)
    viewController?.displayRecipe(viewModel: viewModel)
  }
}
