//
//  WorkoutInteractor.swift
//  CoreBlast
//
//  Created by Riccardo Washington on 1/26/20.
//  Copyright (c) 2020 Riccardo Washington. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol WorkoutBusinessLogic {
  func fetchWorkout(request: WorkoutInfo.FetchWorkout.Request)
}

protocol WorkoutDataStore {
  var workout: Workout? { get set }
  var exercises: [Exercise] { get set }
}

class WorkoutInteractor: WorkoutBusinessLogic, WorkoutDataStore {
    
  var presenter: WorkoutPresentationLogic?
  var worker: WorkoutWorker?
  var workout: Workout?
  var exercises: [Exercise] = []
    
  
  // MARK: Do something
  
  func fetchWorkout(request: WorkoutInfo.FetchWorkout.Request) {
    worker = WorkoutWorker(dataStore: exercises)
    worker?.fetchWorkout(completion: { (workout) in
        let response = WorkoutInfo.FetchWorkout.Response(workout: workout)
        self.presenter?.presentWorkout(response: response)
    })
  }
}
