//
//  WorkoutRouter.swift
//  CoreBlast
//
//  Created by Riccardo Washington on 1/26/20.
//  Copyright (c) 2020 Riccardo Washington. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WorkoutRoutingLogic {
  func routeToPreWorkoutScene()
}

protocol WorkoutDataPassing {
  var dataStore: WorkoutDataStore? { get }
}

class WorkoutRouter: NSObject, WorkoutRoutingLogic, WorkoutDataPassing {
    
  weak var viewController: WorkoutViewController?
  var dataStore: WorkoutDataStore?
  
  // MARK: Routing
    
    func routeToPreWorkoutScene() {
        guard let source = viewController else { return }
        let destination = PreWorkoutViewController()
        navigateToPreWorkoutScene(source: source, destination: destination)
    }

  // MARK: Navigation
  
  private func navigateToPreWorkoutScene(source: WorkoutViewController, destination: PreWorkoutViewController) {
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
//  private func passDataToSomewhere(source: WorkoutDataStore, destination: inout SomewhereDataStore) {
//   // destination.name = source.name
//  }
}
