//
//  WorkoutModels.swift
//  CoreBlast
//
//  Created by Riccardo Washington on 1/26/20.
//  Copyright (c) 2020 Riccardo Washington. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum WorkoutInfo
{
    // MARK: Use cases
    
    enum FetchWorkout {
        struct Request {
            var exercises: [Exercise]
        }
        struct Response {
            var workout: Workout
        }
        struct ViewModel {
            struct WorkoutDetails {
                let nextWorkout: String
                let secondsOfRest: TimeInterval
                let secondsOfExercise: TimeInterval
                let setDuration: TimeInterval
                let workoutDuration: String
                let workoutDurationDouble: TimeInterval
                let numberOfSets: String
                let exercises: [Exercise]
            }
            var workoutDetails: WorkoutDetails
        }
    }
}
