//
//  MealPlanDetailsInteractorTests.swift
//  CoreBlastFY
//
//  Created by Riccardo Washington on 4/18/20.
//  Copyright (c) 2020 Riccardo Washington. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import CoreBlastFY
import XCTest

class MealPlanDetailsInteractorTests: XCTestCase {
  // MARK: Subject under test
  
  var sut: MealPlanDetailInteractor!
  
  // MARK: Test lifecycle
  
  override func setUp() {
    super.setUp()
    setupMealPlanDetailsInteractor()
  }
  
  override func tearDown() {
    super.tearDown()
    sut = nil
  }
  
  // MARK: Test setup
  
  func setupMealPlanDetailsInteractor() {
    sut = MealPlanDetailInteractor()
  }
  
  // MARK: Test doubles
  
  class MealPlanDetailsPresentationLogicSpy: MealPlanDetailPresentationLogic {
    var presentSomethingCalled = false
    
    func presentMealPlanDetails(response: MealPlanDetail.FetchDetails.Response) {
      presentSomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testFetchMealPlanDetails() {
    // Given
    let spy = MealPlanDetailsPresentationLogicSpy()
    sut.presenter = spy
    sut.mealPlan = MealPlan(title: "hey", summary: "hey", description: "hey", image: nil, tip: "")
    let request = MealPlanDetail.FetchDetails.Request()
    
    // When
    sut.fetchMealPlanDetails(request: request)
    
    // Then
    XCTAssertTrue(spy.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
  }
}
