//
//  MealPlanDetailsPresenterTests.swift
//  CoreBlastFY
//
//  Created by Riccardo Washington on 4/18/20.
//  Copyright (c) 2020 Riccardo Washington. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import CoreBlastFY
import XCTest

class MealPlanDetailsPresenterTests: XCTestCase {
  // MARK: Subject under test
  
  var sut: MealPlanDetailPresenter!
  
  // MARK: Test lifecycle
  
  override func setUp() {
    super.setUp()
    setupMealPlanDetailsPresenter()
  }
  
  override func tearDown() {
    super.tearDown()
    sut = nil
  }
  
  // MARK: Test setup
  
  func setupMealPlanDetailsPresenter() {
    sut = MealPlanDetailPresenter()
  }
  
  // MARK: Test doubles
  
  class MealPlanDetailsDisplayLogicSpy: MealPlanDetailDisplayLogic {
    var displaySomethingCalled = false
    
    func displayMealPlanDetails(viewModel: MealPlanDetail.FetchDetails.ViewModel) {
      displaySomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testPresentSomething() {
    // Given
    let spy = MealPlanDetailsDisplayLogicSpy()
    sut.viewController = spy
    let mockMp = MealPlan(title: "hey", summary: "heyehey", imageData: nil, description: "desc")
    let response = MealPlanDetail.FetchDetails.Response(mealPlan: mockMp)
    
    // When
    sut.presentMealPlanDetails(response: response)
    
    // Then
    XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
  }
}
