//
//  PreWorkoutViewController.swift
//  CoreBlast
//
//  Created by Riccardo Washington on 1/25/20.
//  Copyright (c) 2020 Riccardo Washington. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PreWorkoutDisplayLogic: class {
    func displayPreWorkoutViewModel(viewModel: PreWorkout.FetchUser.ViewModel)
}

class PreWorkoutViewController: UIViewController, PreWorkoutDisplayLogic
{
    var interactor: (PreWorkoutBusinessLogic& PreWorkoutDataStore)?
    var router: (NSObjectProtocol & PreWorkoutRoutingLogic & PreWorkoutDataPassing)?
    
    var displayedPreWorkoutData: PreWorkout.FetchUser.ViewModel.UserDetails?
    
    // MARK: Views
    
    private var preworkoutView: PreWorkoutView?
    private var loadingView: LoadingView?
    private var loadingSpinner: UIActivityIndicatorView?
    private var exerciseLoadingView: ExercisesLoadingView?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Routing
    
    func routeToWorkoutScene() {
        router?.routeToWorkoutScene()
    }
    
    private func removeLoadingView() {
        loadingView?.removeFromSuperview()
        loadingView = nil
    }
    
    private func displayLoadingView() {
        loadingView = LoadingView(frame: .zero)
        view.addSubview(loadingView!)
        self.tabBarController?.tabBar.isHidden = true
        preworkoutView?.alpha = 0
        preworkoutView?.isHidden = true
        loadingView!.translatesAutoresizingMaskIntoConstraints = false
        loadingView!.topAnchor.constraint(equalTo: view.topAnchor).isActive = true
        loadingView!.leadingAnchor.constraint(equalTo: view.leadingAnchor).isActive = true
        loadingView!.bottomAnchor.constraint(equalTo: view.bottomAnchor).isActive = true
        loadingView!.trailingAnchor.constraint(equalTo: view.trailingAnchor).isActive = true
        loadingView!.runTimer { [weak self] in
            self?.removeLoadingView()
            self?.routeToWorkoutScene()
        }
    }
    
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        registerObservers()
    }

    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
            fetchUserInfo()
            setupTipIcon()
            self.tabBarController?.tabBar.isHidden = false
        
        if ExerciseStorage.exercises.count <= 0 {
            exerciseLoadingView = ExercisesLoadingView()
            view.addSubview(exerciseLoadingView!)
            exerciseLoadingView?.fillSuperview()
        }
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = PreWorkoutInteractor()
        let presenter = PreWorkoutPresenter()
        let router = PreWorkoutRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.preWorkoutDataStore = interactor
        setupNavigationBar()
        
    }
    
    let tipIcon = UIButton(type: .detailDisclosure)
    
    private func setupTipIcon() {
        tipIcon.tintColor = .goatBlue
        tipIcon.addTarget(self, action: #selector(showTip), for: .touchDown)
        tipIcon.contentVerticalAlignment = .fill
        tipIcon.contentHorizontalAlignment = .fill
        
        addTipIcon()
    }
    
    @objc private func workoutComplete() {
        AlertController.createAlert(errorMessage: "Keep up the hard work!\nConsistency is key!", title: "Congratulations 💪", viewController: self, actionTitle: "🎯")
    }
    
    @objc private func showWorkoutVC() {
        interactor?.exercises = ExerciseStorage.exercises
        DispatchQueue.main.async { [weak self] in
            self?.exerciseLoadingView?.removeFromSuperview()
            self?.exerciseLoadingView = nil
            self?.view.setNeedsDisplay()
        }
    }
    
    @objc private func showTip() {
        AlertController.createAlert(errorMessage: "Warming up or jogging for 10 minutes prior to workout will greatly increase productivity of workout!", title: "Workout Tip", viewController: self)
    }
    
    private func registerObservers() {
        NotificationCenter.default.addObserver(self, selector: #selector(workoutComplete), name: workoutCompleteNotification2, object: nil)
        NotificationCenter.default.addObserver(self, selector: #selector(showWorkoutVC), name: exerciseLoadedNotification, object: nil)
    }
    
    private func addTipIcon() {
        navigationController?.navigationBar.addSubview(tipIcon)
        tipIcon.centerYInSuperview()
        tipIcon.trailingAnchor.constraint(equalTo:  (navigationController?.navigationBar.trailingAnchor)!, constant: -8).isActive = true
        tipIcon.widthAnchor.constraint(equalToConstant: 25).isActive = true
        tipIcon.heightAnchor.constraint(equalToConstant: 25).isActive = true
        
    }
    
    private func setupNavigationBar() {
        navigationItem.title = "Workout"
        view.backgroundColor = .black
    }
    @objc private func startWorkout() {
            displayLoadingView()
    }
    
    private func setupPreWorkoutUI(viewModel: PreWorkout.FetchUser.ViewModel) {
        
        if let pwv = preworkoutView, view.subviews.contains(pwv) {
            preworkoutView?.removeFromSuperview()
            preworkoutView = nil
        }
        preworkoutView = PreWorkoutView(viewModel: viewModel)
        guard let preworkoutView = preworkoutView else { return }
        view.addSubview(preworkoutView)
        let gesture = UITapGestureRecognizer(target: self, action: #selector(startWorkout))
        preworkoutView.addGestureRecognizer(gesture)
        
        preworkoutView.preWorkoutViewController = self
        preworkoutView.translatesAutoresizingMaskIntoConstraints = false
        preworkoutView.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor).isActive = true
        preworkoutView.leadingAnchor.constraint(equalTo: view.leadingAnchor).isActive = true
        preworkoutView.bottomAnchor.constraint(equalTo: view.bottomAnchor).isActive = true
        preworkoutView.trailingAnchor.constraint(equalTo: view.trailingAnchor).isActive = true
        
        //TO DO: - use reusable version
//        if let user = UserAPI.user, user.totalPoints > user.la
        UIView.animate(withDuration: 1.0) { [weak self] in
        self?.preworkoutView?.totalPointsLevel.transform = CGAffineTransform(scaleX: 5, y: 5)
        self?.preworkoutView?.totalPointsLevel.transform = .identity
        }
    }
    
    // MARK: Do something
    
    func displayPreWorkoutViewModel(viewModel: PreWorkout.FetchUser.ViewModel) {
        let viewModel = viewModel
        setupPreWorkoutUI(viewModel: viewModel)
    }
    
    private func displayLoadingSpinner() {
        loadingSpinner = UIActivityIndicatorView(style: .large)
        loadingSpinner?.color = .lightGray
        loadingSpinner?.startAnimating()
        view.addSubview(loadingSpinner!)
        
        loadingSpinner?.translatesAutoresizingMaskIntoConstraints = false
        loadingSpinner?.centerXAnchor.constraint(equalTo: view.centerXAnchor).isActive = true
        loadingSpinner?.centerYAnchor.constraint(equalTo: view.centerYAnchor).isActive = true
        
    }
    
    private func removeLoadingSpinner() {
        loadingSpinner?.stopAnimating()
        loadingSpinner?.removeFromSuperview()
        loadingSpinner = nil
    }
    
    private func fetchUserInfo() {
        let request = PreWorkout.FetchUser.Request()
        interactor?.fetchUserInfo(request: request)
    }
    
    private func showFailureAlert(title: String, message: String)
    {
        let alertController = UIAlertController(title: title, message: message, preferredStyle: .alert)
        let alertAction = UIAlertAction(title: "OK", style: .default, handler: nil)
        alertController.addAction(alertAction)
        showDetailViewController(alertController, sender: nil)
    }
    
}
