//
//  PreWorkoutPresenter.swift
//  CoreBlast
//
//  Created by Riccardo Washington on 1/25/20.
//  Copyright (c) 2020 Riccardo Washington. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PreWorkoutPresentationLogic {
  func presentUser(response: PreWorkout.FetchUser.Response)
}

class PreWorkoutPresenter: PreWorkoutPresentationLogic {
  weak var viewController: PreWorkoutDisplayLogic?
    
let dateFormatter: DateFormatter = {
      let dateFormatter = DateFormatter()
      dateFormatter.locale = Locale(identifier: "en_US_POSIX")
      dateFormatter.dateFormat = "HH:mm"
      dateFormatter.timeStyle = .short
      return dateFormatter
    }()
    
  // MARK: Do something
  
  func presentUser(response: PreWorkout.FetchUser.Response) {
    
    let user = response.user
    
    let displayedUserInfo = PreWorkout.FetchUser.ViewModel.UserDetails(name: user.name, coreLevel: user.coreLevel.rawValue, totalPoints: "\(user.totalPoints)", nextLevel: "\(user.nextLevelUp)", nextWorkoutDate: dateFormatter.string(from: user.nextWorkout))
    let viewModel = PreWorkout.FetchUser.ViewModel(userDetails: displayedUserInfo)
    viewController?.displayPreWorkoutViewModel(viewModel: viewModel)
  }
}
