//
//  PreWorkoutModels.swift
//  CoreBlast
//
//  Created by Riccardo Washington on 1/25/20.
//  Copyright (c) 2020 Riccardo Washington. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum PreWorkout {
    
  // MARK: Use cases
  
  enum FetchUser {
    struct Request {
    }
    
    struct Response {
        var user: User
    }
    
    struct ViewModel {
        
        struct UserDetails {
            var name: String?
            var coreLevel: String
            var totalPoints: String
            var nextLevel: String
            var nextWorkoutDate: String
        }
        var userDetails: UserDetails
    }
  }
    
    enum FetchExercises {
        struct Request {
        }
        
        struct Response {
            var exercises: [Exercise]
        }
        
        struct ViewModel {
            
        }
    }
}
