//
//  MealPlanDetailRouter.swift
//  CoreBlastFY
//
//  Created by Riccardo Washington on 4/18/20.
//  Copyright (c) 2020 Riccardo Washington. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MealPlanDetailRoutingLogic { }

protocol MealPlanDetailDataPassing {
    var dataStore: MealPlanDetailDataStore? { get }
}

class MealPlanDetailRouter: NSObject, MealPlanDetailRoutingLogic, MealPlanDetailDataPassing {
    
    weak var viewController: MealPlanDetailViewController?
    var dataStore: MealPlanDetailDataStore?
    
    // MARK: Routing
    
}
