//
//  MealPlanDetailPresenter.swift
//  CoreBlastFY
//
//  Created by Riccardo Washington on 4/18/20.
//  Copyright (c) 2020 Riccardo Washington. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MealPlanDetailPresentationLogic {
  func presentMealPlanDetails(response: MealPlanDetail.FetchDetails.Response)
}

class MealPlanDetailPresenter: MealPlanDetailPresentationLogic {
  weak var viewController: MealPlanDetailDisplayLogic?
  
  // MARK: Do something
  
  func presentMealPlanDetails(response: MealPlanDetail.FetchDetails.Response) {
    let mealPlan = response.mealPlan
    let displayedPlan = MealPlanDetail.FetchDetails.ViewModel.DisplayMealPlanDetails.init(title: mealPlan.title, summary: mealPlan.summary, description: mealPlan.description, planImage: mealPlan.image)
    let viewModel = MealPlanDetail.FetchDetails.ViewModel(displayedPlan: displayedPlan)
    viewController?.displayMealPlanDetails(viewModel: viewModel)
  }
}
