//
//  NotificationsPresenter.swift
//  CoreBlastFY
//
//  Created by Riccardo Washington on 4/13/20.
//  Copyright (c) 2020 Riccardo Washington. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NotificationsPresentationLogic {
  func presentSelectedTime(response: Notifications.SelectedTime.Response)
}

class NotificationsPresenter: NotificationsPresentationLogic {
  weak var viewController: NotificationsDisplayLogic?
  
  // MARK: Do something
  
  func presentSelectedTime(response: Notifications.SelectedTime.Response) {
    let selectedDate = response.selectedDate
    let viewModel = Notifications.SelectedTime.ViewModel(selectedDate: selectedDate)
    viewController?.displaySelectedTime(viewModel: viewModel)
  }
}
