//
//  NotificationsWorker.swift
//  CoreBlastFY
//
//  Created by Riccardo Washington on 4/13/20.
//  Copyright (c) 2020 Riccardo Washington. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class NotificationsWorker {
    
    func fetchSelectedTime(completion: @escaping(Date) -> Void) {
        let user = UserManager.loadUserFromFile()
        completion(user.selectedTime ?? Date())
  }
}
