//
//  NotificationsModels.swift
//  CoreBlastFY
//
//  Created by Riccardo Washington on 4/13/20.
//  Copyright (c) 2020 Riccardo Washington. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Notifications {
  // MARK: Use cases
  
  enum SelectedTime {
    struct Request {
    }
    struct Response {
        var selectedDate: Date
    }
    struct ViewModel {
        var selectedDate: Date
    }
  }
}
