//
//  MealPlansViewController.swift
//  CoreBlastFY
//
//  Created by Riccardo Washington on 4/16/20.
//  Copyright (c) 2020 Riccardo Washington. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import StoreKit

protocol MealPlansDisplayLogic: class {
    func displayPlans(viewModel: MealPlans.GetPlan.ViewModel)
}

class MealPlansViewController: UICollectionViewController, MealPlansDisplayLogic {
    var interactor: (MealPlansBusinessLogic & MealPlansDataStore)?
    var router: (NSObjectProtocol & MealPlansRoutingLogic & MealPlansDataPassing)?
    var productId: String?
    
    override var prefersStatusBarHidden: Bool {
        return true
    }
    
    // MARK: Object lifecycle
    
    init() {
        super.init(collectionViewLayout: UICollectionViewFlowLayout())
        SKPaymentQueue.default().add(self)
        collectionView.register(MealPlansOverviewCollectionViewCell.self, forCellWithReuseIdentifier: MealPlansOverviewCollectionViewCell.id)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = MealPlansInteractor()
        let presenter = MealPlansPresenter()
        let router = MealPlansRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    func routeToMealPlanDetails() {
        router?.routeToMealPlanDetailController()
    }
    
    // MARK: View lifecycle
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        getPlans()
    }
    
    // MARK: Do something
    private var loadingSpinner: UIActivityIndicatorView?
    
    private func displayLoadingSpinner() {
        loadingSpinner = UIActivityIndicatorView(style: .large)
        loadingSpinner?.color = .white
        loadingSpinner?.startAnimating()
        view.addSubview(loadingSpinner!)
        
        loadingSpinner?.translatesAutoresizingMaskIntoConstraints = false
        loadingSpinner?.centerXAnchor.constraint(equalTo: view.centerXAnchor).isActive = true
        loadingSpinner?.centerYAnchor.constraint(equalTo: view.centerYAnchor).isActive = true
        
    }
    
    var displayedPlans: [MealPlans.GetPlan.ViewModel.PlanOverview] = []
    
    private func getPlans() {
        let request = MealPlans.GetPlan.Request()
        interactor?.getPlansOverview(request: request)
    }
    
    func displayPlans(viewModel: MealPlans.GetPlan.ViewModel) {
        displayedPlans = viewModel.planOverViews
        collectionView.reloadData()
    }
}

extension MealPlansViewController: UICollectionViewDelegateFlowLayout {
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
        return .init(width: view.frame.width - 32, height: MealPlansViewController.Dimensions.mealPlanCellSize)
    }
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, minimumLineSpacingForSectionAt section: Int) -> CGFloat {
        return 32
    }
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, insetForSectionAt section: Int) -> UIEdgeInsets {
        return .init(top: 32, left: 0, bottom: 32, right: 0)
    }
}

extension MealPlansViewController {
    override func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return displayedPlans.count
    }
    
    override func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        guard let cell = collectionView.dequeueReusableCell(withReuseIdentifier: MealPlansOverviewCollectionViewCell.id, for: indexPath) as? MealPlansOverviewCollectionViewCell else {
            return UICollectionViewCell() }
        let plan = displayedPlans[indexPath.item]
        cell.configure(item: plan)
        return cell
        
    }
}

extension MealPlansViewController {
    override func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        let plans = InAppIds.all[indexPath.item]
        productId = plans

        if let productId = productId, isPurchased(with: productId) {
            routeToMealPlanDetails()
        } else if let productId = productId {
            buyMealPlan(with: productId)
        }


        if productId == nil {
            routeToMealPlanDetails()
        }
    }
}

extension MealPlansViewController {
    struct Dimensions {
        static let cellSize: CGFloat = 100
        static let mealPlanCellSize: CGFloat = 300
    }
}

// MARK: In App Purchases

extension MealPlansViewController: SKPaymentTransactionObserver {
    func paymentQueue(_ queue: SKPaymentQueue, updatedTransactions transactions: [SKPaymentTransaction]) {
        if productId != nil {
        for transaction in transactions {
            switch transaction.transactionState {
            case .purchasing:
                DispatchQueue.main.async {
                    self.displayLoadingSpinner()
                }
            case .purchased:
                SKPaymentQueue.default().finishTransaction(transaction)
                UserDefaults.standard.set(true, forKey: productId!)
                loadingSpinner?.stopAnimating()
                loadingSpinner = nil
            case .failed:
                loadingSpinner?.stopAnimating()
                loadingSpinner = nil
                if let error = transaction.error {
                let errorDesc = error.localizedDescription
                    AlertController.createAlert(errorMessage: errorDesc, viewController: self)
                }
            case .restored:
                loadingSpinner?.stopAnimating()
                loadingSpinner = nil
                    UserDefaults.standard.set(true, forKey: productId!)
                    SKPaymentQueue.default().finishTransaction(transaction)
            default: break
            }
        }
        }
    }
    
    func isPurchased(with id: String) -> Bool {
        let purchaseRecipt = UserDefaults.standard.bool(forKey: id)
        return purchaseRecipt
    }
    
    func buyMealPlan(with id: String) {
        if SKPaymentQueue.canMakePayments() {
            let paymentRequest = SKMutablePayment()
            paymentRequest.productIdentifier = id
            SKPaymentQueue.default().add(paymentRequest)
        } else {
            AlertController.createAlert(errorMessage: "Sorry... seems like this device can't make payments", viewController: self)
        }
    }
}
