//
//  MealPlansModels.swift
//  CoreBlastFY
//
//  Created by Riccardo Washington on 4/16/20.
//  Copyright (c) 2020 Riccardo Washington. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MealPlans {
    // MARK: Use cases
    
    enum GetPlan
    {
        struct Request
        {
        }
        struct Response
        {
            var mealPlans: [MealPlan]
        }
        struct ViewModel
        {
            struct PlanOverview {
                var title: String
                var summary: String
                var image: UIImage?
            }
            var planOverViews: [PlanOverview]
        }
    }
}
