//
//  MealPlansWorkerTests.swift
//  CoreBlastFY
//
//  Created by Riccardo Washington on 4/16/20.
//  Copyright (c) 2020 Riccardo Washington. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import CoreBlastFY
import XCTest

class MealPlansWorkerTests: XCTestCase {
  // MARK: Subject under test
  
  var sut: MealPlansWorker!
  
  // MARK: Test lifecycle
  
  override func setUp() {
    super.setUp()
    setupMealPlansWorker()
  }
  
  override func tearDown() {
    super.tearDown()
    sut = nil
  }
  
  // MARK: Test setup
  
  func setupMealPlansWorker() {
    let overviewStore = MealPlanAPI()
    sut = MealPlansWorker(dataStore: overviewStore)
  }
  
  // MARK: Test doubles
  
  // MARK: Tests
  
  func testFetchMealPlanOverview() {
    // Given
    var mealPlan: [MealPlan]?
    // When
    sut.getPlansOverview { (mealplans, error) in
        mealPlan = mealplans
    }
    
    // Then
     XCTAssertNotNil(mealPlan, "shouldnt be nil")
  }
}
