//
//  MealPlansInteractorTests.swift
//  CoreBlastFY
//
//  Created by Riccardo Washington on 4/16/20.
//  Copyright (c) 2020 Riccardo Washington. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import CoreBlastFY
import XCTest

class MealPlansInteractorTests: XCTestCase {
  // MARK: Subject under test
  
  var sut: MealPlansInteractor!
  
  // MARK: Test lifecycle
  
  override func setUp() {
    super.setUp()
    setupMealPlansInteractor()
  }
  
  override func tearDown() {
    super.tearDown()
    sut = nil
  }
  
  // MARK: Test setup
  
  func setupMealPlansInteractor() {
    sut = MealPlansInteractor()
  }
  
  // MARK: Test doubles
  
  class MealPlansPresentationLogicSpy: MealPlansPresentationLogic
  {
    func presentMealPlansOverview(response: MealPlans.GetPlan.Response) {
        presentSomethingCalled = true
    }
    
    var presentSomethingCalled = false

  }
  
  // MARK: Tests
  
  func testDoSomething() {
    // Given
    let spy = MealPlansPresentationLogicSpy()
    sut.presenter = spy
    let request = MealPlans.GetPlan.Request()
    
    // When
    sut.getPlansOverview(request: request)
    
    // Then
    XCTAssertTrue(spy.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
  }
}
