//
//  MealPlansPresenterTests.swift
//  CoreBlastFY
//
//  Created by Riccardo Washington on 4/16/20.
//  Copyright (c) 2020 Riccardo Washington. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import CoreBlastFY
import XCTest

class MealPlansPresenterTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: MealPlansPresenter!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupMealPlansPresenter()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupMealPlansPresenter()
  {
    sut = MealPlansPresenter()
  }
  
  // MARK: Test doubles
  
  class MealPlansDisplayLogicSpy: MealPlansDisplayLogic
  {
    var displaySomethingCalled = false
    
    func displaySomething(viewModel: MealPlans.Something.ViewModel)
    {
      displaySomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testPresentSomething()
  {
    // Given
    let spy = MealPlansDisplayLogicSpy()
    sut.viewController = spy
    let response = MealPlans.Something.Response()
    
    // When
    sut.presentSomething(response: response)
    
    // Then
    XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
  }
}
