//
//  WorkoutOfTheDayInteractor.swift
//  CoreBlastFY
//
//  Created by Riccardo Washington on 8/8/21.
//  Copyright (c) 2021 Riccardo Washington. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WorkoutOfTheDayBusinessLogic
{
  func doSomething(request: WorkoutOfTheDay.Something.Request)
}

protocol WorkoutOfTheDayDataStore
{
  //var name: String { get set }
}

class WorkoutOfTheDayInteractor: WorkoutOfTheDayBusinessLogic, WorkoutOfTheDayDataStore
{
  var presenter: WorkoutOfTheDayPresentationLogic?
  var worker: WorkoutOfTheDayWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: WorkoutOfTheDay.Something.Request)
  {
    worker = WorkoutOfTheDayWorker()
    worker?.doSomeWork()
    
    let response = WorkoutOfTheDay.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
