//
//  WorkoutOfTheDayPresenter.swift
//  CoreBlastFY
//
//  Created by Riccardo Washington on 8/8/21.
//  Copyright (c) 2021 Riccardo Washington. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WorkoutOfTheDayPresentationLogic
{
  func presentSomething(response: WorkoutOfTheDay.Something.Response)
}

class WorkoutOfTheDayPresenter: WorkoutOfTheDayPresentationLogic
{
  weak var viewController: WorkoutOfTheDayDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: WorkoutOfTheDay.Something.Response)
  {
    let viewModel = WorkoutOfTheDay.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
