//
//  WorkoutOfTheDayModels.swift
//  CoreBlastFY
//
//  Created by Riccardo Washington on 8/8/21.
//  Copyright (c) 2021 Riccardo Washington. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum WorkoutOfTheDay
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
    }
    struct Response
    {
    }
    struct ViewModel
    {
    }
  }
}
