//
//  WorkoutOfTheDayRouter.swift
//  CoreBlastFY
//
//  Created by Riccardo Washington on 8/8/21.
//  Copyright (c) 2021 Riccardo Washington. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol WorkoutOfTheDayRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol WorkoutOfTheDayDataPassing
{
  var dataStore: WorkoutOfTheDayDataStore? { get }
}

class WorkoutOfTheDayRouter: NSObject, WorkoutOfTheDayRoutingLogic, WorkoutOfTheDayDataPassing
{
  weak var viewController: WorkoutOfTheDayViewController?
  var dataStore: WorkoutOfTheDayDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: WorkoutOfTheDayViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: WorkoutOfTheDayDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
