//
//  PreWorkoutPresenterTests.swift
//  CoreBlastFY
//
//  Created by Riccardo Washington on 4/16/20.
//  Copyright (c) 2020 Riccardo Washington. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import CoreBlastFY
import XCTest

class PreWorkoutPresenterTests: XCTestCase {
  // MARK: Subject under test
  
  var sut: PreWorkoutPresenter!
  
  // MARK: Test lifecycle
  
  override func setUp() {
    super.setUp()
    setupPreWorkoutPresenter()
  }
  
  override func tearDown() {
    super.tearDown()
    sut = nil
  }
  
  // MARK: Test setup
  
  func setupPreWorkoutPresenter() {
    sut = PreWorkoutPresenter()
  }
  
  // MARK: Test doubles
  
  class PreWorkoutDisplayLogicSpy: PreWorkoutDisplayLogic {
    var displaySomethingCalled = false
    
    func displayPreWorkoutViewModel(viewModel: PreWorkout.FetchUser.ViewModel) {
      displaySomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testPresentUser() {
    // Given
    let spy = PreWorkoutDisplayLogicSpy()
    sut.viewController = spy
    let mockUser = User()
    let response = PreWorkout.FetchUser.Response(user: mockUser)
    
    // When
    sut.presentUser(response: response)
    
    // Then
    XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
  }
}
