//
//  PreWorkoutWorkerTests.swift
//  CoreBlastFY
//
//  Created by Riccardo Washington on 4/16/20.
//  Copyright (c) 2020 Riccardo Washington. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import CoreBlastFY
import XCTest

class PreWorkoutWorkerTests: XCTestCase {
  // MARK: Subject under test
  
  var sut: PreWorkoutWorker!
  
  // MARK: Test lifecycle
  
  override func setUp() {
    super.setUp()
    setupPreWorkoutWorker()
  }
  
  override func tearDown() {
    super.tearDown()
    sut = nil
  }
  
  // MARK: Test setup
  
  func setupPreWorkoutWorker() {
    let userApi = UserAPI()
    sut = PreWorkoutWorker(userInfoStore: userApi)
  }
  
  // MARK: Test doubles
  
  // MARK: Tests
  
  func testFetchUserInfoSuccess() {
    // Given
    var newUser: User?
    sut.fetchUserInfo { (user, _) in
        newUser = user
    }
    // When
    
    // Then
    XCTAssertNotNil(newUser, "shouldnt be nil")
  }
    
    func testFetchUserInfoFails() {
      // Given
      var newUser: User?
      sut.fetchUserInfo { (nil, error) in
          newUser = nil
      }
      // When
      
      // Then
      XCTAssertNil(newUser, "shouldnt be nil")
    }
}
